include: package:solid_lints/analysis_options.yaml

analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - 'build/**'
    - '.dart_tool/**'
    - 'lib/generated/**'

  errors:
    missing_return: error
    dead_code: error
    unused_local_variable: warning
    comment_references: ignore
    public_member_api_docs: ignore
    always_use_package_imports: ignore

linter:
  rules:
    # ------------------------------------------------------------------------------
    # Performance & Efficiency
    # ------------------------------------------------------------------------------
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_declarations: true

    # ------------------------------------------------------------------------------
    # Readability & Style
    # ------------------------------------------------------------------------------
    prefer_single_quotes: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sort_constructors_first: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    unnecessary_this: true
    file_names: true
    camel_case_types: true
    constant_identifier_names: true
    non_constant_identifier_names: true

    # ------------------------------------------------------------------------------
    # Error Prevention & Best Practices
    # ------------------------------------------------------------------------------
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_returning_null: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    prefer_conditional_assignment: true
    prefer_null_aware_operators: true
    unnecessary_null_checks: true
    prefer_typing_uninitialized_variables: true
    avoid_unused_constructor_parameters: true
    no_self_assignments: true
    unawaited_futures: true

    # ------------------------------------------------------------------------------
    # Imports & Dependencies
    # ------------------------------------------------------------------------------
    prefer_relative_imports: true
    directives_ordering: true
    implementation_imports: true
    library_prefixes: true

dart_code_metrics:
  metrics-exclude:
    - test/**
    - lib/**.g.dart
    - lib/**.freezed.dart

  rules:
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - always-remove-listener
    - member-ordering
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - arguments-ordering
    - avoid-nested-conditional-expressions

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 100
